env=Environment(CPPPATH=['/usr/include/boost/'],
		CPPDEFINES=['TIXML_USE_STL'],
		LIBS=['boost_unit_test_framework'],
		CXXFLAGS="-std=c++11 -g3 -O0 -Wall -Wextra"
		)
env.Program(['test_move_object.cpp', '../CellObject.cpp', '../CyclicQueue.cpp', '../DnaGenerator.cpp', '../DnaUnit.cpp', '../FieldCell.cpp', '../Field.cpp', '../Tui.cpp', '../Unit.cpp'])
